<!-- Include file for all JScript -->
<!--
Call Google CDN using API key
Documentation: http://code.google.com/apis/ajaxlibs/documentation/index.html#jqueryUI
-->
<script src="http://www.google.com/jsapi?key=ABQIAAAA6vZeEkM0KyP39fzR4WH15BRNqZKDNE222n26MjBSchDpjP7zexRKOru55pKob0TLEZWtrySxbGzXsA" type="text/javascript"></script>
<script type="text/javascript">

// Call & load jQuery and jQuery UI modules

  google.load("jquery", "1.4.2");
  google.load("jqueryui", "1.8.1");
</script>
<!-- Load required scripts -->
<script type="text/javascript" src="../assets/js/jquery/jquery.dimensions.min.js"></script>
<script type="text/javascript" src="../assets/js/jquery/jquery.scrollTo-min.js"></script>
<script type="text/javascript" src="../assets/js/jquery/jquery.serialScroll-min.js"></script>
<script type="text/javascript" src="../assets/js/jquery/preloadCssImages.jQuery_v5.js"></script>
<script type="text/javascript" src="../assets/js/jquery/searchBox.js"></script>
<script type="text/javascript" src="../assets/js/jquery/homepage.js"></script>